gi::pressButton {/scroll/scrollArea/scrollAreaInnerWidget/applications/dmLibraryManager} -in [gi::getWindows 1]
gi::setCurrentIndex {libs} -index {gf180mcu} -in [gi::getWindows 2]
gi::setItemSelection {libs} -index {gf180mcu} -in [gi::getWindows 2]
gi::setCurrentIndex {cells} -index {nmoscap_3p3} -in [gi::getWindows 2]
gi::setItemSelection {cells} -index {nmoscap_3p3} -in [gi::getWindows 2]
gi::setCurrentIndex {views} -index {symbol} -in [gi::getWindows 2]
gi::setItemSelection {views} -index {symbol} -in [gi::getWindows 2]
gi::setCurrentIndex {views} -index {hspiceD} -in [gi::getWindows 2]
gi::setItemSelection {views} -index {hspiceD} -in [gi::getWindows 2]
gi::setCurrentIndex {cells} -index {npolyf_u} -in [gi::getWindows 2]
gi::setItemSelection {cells} -index {npolyf_u} -in [gi::getWindows 2]
gi::executeAction {menuPreShow} -in [gi::getWindows 2]
exit
